### ISSUE TITLE
I have problem 

### ISSUE THREAD

**Issue by Prekarshamaxx123** [Hannan-404/DLTX#1]
==============================
Traceback (most recent call last):
  File "DELET.py", line 219, in init DELET
  File "DELET.py", line 155, in DELET.file
  File "DELET.py", line 164, in DELET.star                                                       ValueError: need more than 2 values to unpack                                                    ~/DLTX $

**Comment by Hannan-404** [comment]
INput With cookies

**Comment by Prekarshamaxx123** [comment]
Can you understand more?
